export * from './ServisIcons/ServisIcons'
export * from './MobileApp/MobilApp'
export * from './Q&A/QA'
export * from './slider/Slider'
export * from './Footer/Footer'
export * from './Header/Header'
export * from './VisaList/VisaList'
export * from './Header/logo'