export * from './ServisIcons/ServisIcons'
export * from './MobileApp/MobilApp'
export * from './Q&A/QA'
export * from './slider/Slider'
export * from './Footer/Footer'
export * from './NavBar/NavBar'
export * from './VisaList/VisaList'
export * from './TravelServicesMenu/TravelServicesMenu'